# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'skyPractice' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for skyPractice

#  target 'skyPracticeTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
#  target 'skyPracticeUITests' do
#    inherit! :search_paths
#    # Pods for testing
#  end


    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'



end


